dist: trusty
sudo: required

language: node_js
node_js: "8"

os:
  - linux

script:
  - npm -v

before_deploy:
  - npm run build

deploy:
  provider: releases
  api-key: "c589cebd96f6d4a6ed5c6fc350ffe59b78ddfda9"
  file: README.md
  skip_cleanup: true
  on:
    tags: true