sudo: required

language: node_js
node_js: "8"

os:
  - linux

script:
  - npm run build

deploy:
  provider: releases
  api-key: "c589cebd96f6d4a6ed5c6fc350ffe59b78ddfda9"
  file: 
    - "LICENSE"
  skip_cleanup: true
  on:
    repo: shangxinbo/treering-windows
    tags: true