dist: trusty
sudo: required

language: node_js
node_js: "8"

os:
  - linux

script:
  - npm -v

before_deploy:
  - npm run build

deploy:
  provider: releases
  api-key: "e65e206137d7dfbe24b8b357023fb81553584fc8"
  file: README.md
  skip_cleanup: true
  on:
    tags: true