dist: trusty
sudo: required
language: node_js
node_js: '8'
os:
- linux
script:
- npm -v
before_deploy:
- npm run build
deploy:
  provider: releases
  api_key:
    secure: mol69b20JzDq6TUFvGz35igtovRRuDHpUNwMFJar5TR0w+LzCNVMBZ+GZRYvX+qS43PWHITKfmBrIttSkOz5k6RhzWg23eW78FRkKoCYYZRBsxjXm9c7n6px9wDnbPLqZ9XeXJ+QQarii1uDZU864xPXrO+3h/jSw4Ig/JR3eIn9rcW0b+pD3vSvNhyYIYGlvU7kb0HMbhzMV8xHTOzPMILwSL3ohggwZLmoD4lxqxQ+BZAwcL8uTkERgbNXZTwc1OkAztvFaIc5/ZWA6zQPpzwjnEeK+CP2kSKBf/p/pQ0W5SbiNp31Yx+F2VIDMxe4qvvIIjodwDQEg7c3xpy3SrAu0m/EgJzH6wT9qzvMz/MCZguUETtfIiSPX7hr0fYWSIppQZruSx3nXUybTpSBeqTfaamG43FwcZo3gbrttvaGqAGrBX5GwPZsRmM+DBneU56mC50ij9aHzAwnQ5powG9t8W/0DM1KY2zXZ26D4cywVJVZAQotn4/yMZLH+rvtUwQl2wc/Ok6bhHetGtFxFg4wS6eDvCQeW1Shv+Sd3xnPN3KhqUeMLL54wlZQsAaoz5kqpvTEuNZ8p+DkAsu+8Is5gShetEgBSeMLU8Ms2LMD5Fk/5Y3hVWLtUs7CtLlc4EGXKSXuV5y1db+QcJNiXTdkwnMX2jMKIbJ8JJGP7Pc=
  file: 'build/*.*'
  skip_cleanup: true
  file_glob: true
  on:
    repo: shangxinbo/treering-windows
    tags: true
